export {
  type GodotVersion,
  MIN_SUPPORTED_VERSION,
  MAX_SUPPORTED_MINOR,
  parseGodotVersion,
  formatVersion,
  compareVersions,
  isVersionCompatible,
  versionCompatibilityMessage,
  getBinaryName,
  getDownloadFilename,
} from "./version.js";

export {
  type DetectionResult,
  detectGodot,
  getArchitecture,
  clearQuarantine,
} from "./detect.js";

export {
  type DownloadOptions,
  type DownloadResult,
  downloadGodot,
  verifySha512,
  computeSha512,
} from "./download.js";

export {
  type GodotCliResult,
  type GodotCliOptions,
  checkOnly,
  runHeadless,
  exportProject,
  getVersion,
  spawnGodotEditor,
  spawnGodotPreview,
} from "./cli.js";

export {
  type GodotProject,
  type CreateProjectOptions,
  isGodotProject,
  parseProjectGodot,
  createProject,
  validateProjectStructure,
} from "./project.js";

export {
  type PreviewStatus,
  type PreviewState,
  type PreviewManager,
  createPreviewManager,
} from "./preview.js";

export {
  parseGodotErrors,
  formatErrorsForAI,
  type GodotError,
} from "./error-parser.js";

export {
  scaffoldProject,
  getAvailableTemplates,
  type ScaffoldOptions,
} from "./scaffold.js";

export {
  type ExportPreset,
  type ExportOptions,
  type ExportResult,
  getExportPresets,
  createDefaultPresets,
  exportProject as exportGodotProject,
  checkExportTemplates,
  getExportTemplateUrl,
} from "./export.js";

export {
  type PluginConfig,
  type GodotPlugin,
  type InstallPluginOptions,
  type PluginInstallResult,
  parsePluginCfg,
  readPluginConfig,
  getEnabledPlugins,
  listPlugins,
  getPlugin,
  installPlugin,
  removePlugin,
  enablePlugin,
  disablePlugin,
  validatePluginStructure,
} from "./plugin-manager.js";

export {
  type WorkLogOperationType,
  type FileChange,
  type WorkLogEntry,
  type WorkLogHead,
  type WorkLogSummary,
  type WorkLogDiff,
  type WorkLogQuery,
  generateEntryId,
  computeContentHash,
  initWorkLog,
  hasWorkLog,
  recordEntry,
  getEntry,
  getLog,
  createBranch,
  listBranches,
  deleteBranch,
  getDiff,
  tagEntry,
  untagEntry,
  getSummary,
  formatEntryOneline,
  formatEntryFull,
  destroyWorkLog,
} from "./work-log.js";

export {
  type BuildPlatform,
  type BuildStatus,
  type BuildProfile,
  type ArtifactType,
  type PlatformConfig,
  type BuildArtifact,
  type PlatformBuildResult,
  type BuildRun,
  type BuildPipelineConfig,
  type BuildPipelineState,
  type BuildHistory,
  type BuildQuery,
  type BuildStats,
  type BuildMatrix,
  type PipelineValidation,
  getDefaultPlatformConfigs,
  getDefaultPlatformConfig,
  getSupportedPlatforms,
  getArtifactType,
  validatePipelineConfig,
  initPipeline,
  hasPipeline,
  getState as getBuildPipelineState,
  updateConfig as updateBuildPipelineConfig,
  getEnabledPlatforms as getBuildEnabledPlatforms,
  setPlatformEnabled,
  addPlatform,
  removePlatform,
  createBuildMatrix,
  executeBuild,
  cancelBuild,
  getRun,
  getHistory as getBuildHistory,
  getStats as getBuildStats,
  getPlatformResult,
  isRunSuccessful,
  getFailedPlatforms,
  getSucceededPlatforms,
  getRunArtifacts,
  pruneRuns,
  formatRunOneline,
  formatRunFull,
  generateBuildSummary,
  destroyPipeline,
} from "./build-pipeline.js";

export {
  type CommitStrategy,
  type FileCategory,
  type TrackedFile,
  type FileSnapshot,
  type CommitChange,
  type AutoCommit,
  type AutoCommitConfig,
  type AutoCommitState,
  type CommitHistory,
  type CommitQuery,
  type CommitStats,
  categorizeFile,
  shouldIgnore,
  scanDirectory,
  initAutoCommit,
  hasAutoCommit,
  getState as getAutoCommitState,
  updateConfig as updateAutoCommitConfig,
  detectChanges,
  generateCommitMessage,
  takeSnapshot,
  createCommit,
  getCommit,
  getHistory,
  addPendingChanges,
  flushPendingChanges,
  shouldCommit,
  startTracking,
  stopTracking,
  getStats as getAutoCommitStats,
  pruneCommits,
  formatCommitOneline,
  formatCommitFull,
  destroyAutoCommit,
} from "./auto-commit.js";

export {
  type ItchChannel,
  type PublishStatus,
  type ItchTarget,
  type ItchPublishConfig,
  type ItchChannelConfig,
  type ButlerInfo,
  type ButlerLoginStatus,
  type ChannelPublishResult,
  type PublishRun,
  type ItchPublishState,
  type PublishHistory,
  type PublishQuery,
  type PublishStats,
  type PublishValidation,
  type PublishOptions,
  parseItchTarget,
  formatItchTarget,
  getDefaultChannels,
  getDefaultChannelNames,
  detectButler,
  checkButlerLogin,
  validatePublishConfig,
  initPublisher,
  hasPublisher,
  getState as getItchPublishState,
  updateConfig as updateItchPublishConfig,
  getEnabledChannels,
  setChannelEnabled,
  addChannel as addItchChannel,
  removeChannel as removeItchChannel,
  buildPushArgs,
  executePublish,
  cancelPublish,
  getRun as getPublishRun,
  getHistory as getPublishHistory,
  getStats as getPublishStats,
  getChannelResult,
  isRunSuccessful as isPublishRunSuccessful,
  getFailedChannels,
  getSucceededChannels,
  pruneRuns as prunePublishRuns,
  formatRunOneline as formatPublishRunOneline,
  formatRunFull as formatPublishRunFull,
  generatePublishSummary,
  destroyPublisher,
  createButlerExecutor,
} from "./itch-publisher.js";

export {
  type MobileStore,
  type MobilePublishStatus,
  type ReleaseTrack,
  type AppStoreReleaseType,
  type MobileStoreConfig,
  type GooglePlayConfig,
  type AppStoreConfig,
  type MobileToolInfo,
  type MobileAuthStatus,
  type StorePublishResult,
  type MobilePublishRun,
  type MobilePublishConfig,
  type MobilePublishState,
  type MobilePublishHistory,
  type MobilePublishQuery,
  type MobilePublishStats,
  type MobilePublishValidation,
  type MobilePublishOptions,
  getDefaultStores,
  getSupportedStoreNames,
  isGooglePlayConfig,
  isAppStoreConfig,
  detectGooglePlayTool,
  detectAppStoreTool,
  checkGooglePlayAuth,
  checkAppStoreAuth,
  validateArtifact,
  validateMobilePublishConfig,
  initMobilePublisher,
  hasMobilePublisher,
  getMobilePublishState,
  updateMobilePublishConfig,
  getEnabledStores,
  setStoreEnabled,
  addStore,
  removeStore,
  buildGooglePlayUploadArgs,
  buildAppStoreUploadArgs,
  buildUploadArgs,
  executeMobilePublish,
  cancelMobilePublish,
  getMobileRun,
  getMobileHistory,
  getMobileStats,
  getStoreResult,
  isMobileRunSuccessful,
  getFailedStores,
  getSucceededStores,
  pruneMobileRuns,
  formatMobileRunOneline,
  formatMobileRunFull,
  generateMobilePublishSummary,
  destroyMobilePublisher,
  createGooglePlayExecutor,
  createAppStoreExecutor,
} from "./mobile-publisher.js";
